"use strict";

const fs = require("fs");
const path = require("path");
const { loadBalance } = require("../src/server/balanceConfig");

const DEFAULT_ROOT = path.join(__dirname, "..");

function generateBalanceArtifacts(root = DEFAULT_ROOT) {
  const balanceSource = path.join(root, "component-balance.json");
  const balanceTarget = path.join(root, "public", "component-balance.generated.json");
  const generatedModule = path.join(root, "public", "src", "generatedBalance.js");

  loadBalance(balanceSource);
  const rawBalance = fs.readFileSync(balanceSource, "utf8");

  fs.mkdirSync(path.dirname(balanceTarget), { recursive: true });
  fs.mkdirSync(path.dirname(generatedModule), { recursive: true });
  fs.copyFileSync(balanceSource, balanceTarget);
  fs.writeFileSync(
    generatedModule,
    `// Generated by netlify-build.js; do not edit.\nexport const GENERATED_BALANCE = ${rawBalance};\n`,
    "utf8"
  );

  return { balanceSource, balanceTarget, generatedModule };
}

if (require.main === module) {
  generateBalanceArtifacts();
  console.log("Generated public balance artifacts from component-balance.json");
}

module.exports = { generateBalanceArtifacts };
